-- =============================================================================
-- TP N°2 - Base de Datos II (UCSE DAR, 2024) - Gestion de Puertos con PostGIS
-- 01_schema.sql : estructura del schema `puertos`
-- =============================================================================
--
-- NOTA SOBRE LA PROCEDENCIA DE ESTE ARCHIVO
--
-- El backup entregado en 2024 (data/DBworld-bp1.backup) no contiene el schema
-- `puertos`: solo conserva la capa `world_countries_generalized` y las tablas
-- de soporte de PostGIS. Este archivo es una RECONSTRUCCION del esquema a
-- partir de:
--
--   * las definiciones de tablas en docs/notas-del-equipo.txt
--   * las consultas y los tipos de columna visibles en docs/informe-tp2-postgis.pdf
--   * el arbol de objetos de pgAdmin en docs/img/10-schema-puertos-pgadmin.jpeg
--
-- La reconstruccion se valida ejecutando sql/04_verificacion.sql, que reproduce
-- los resultados numericos publicados en el informe.
--
-- Las columnas geometricas se llaman `ubicacion` porque asi aparecen en las
-- consultas finales del informe. En las capturas mas tempranas del desarrollo
-- todavia se llamaban `geom`; el nombre cambio durante el trabajo.
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS postgis;

DROP SCHEMA IF EXISTS puertos CASCADE;
CREATE SCHEMA puertos;

-- -----------------------------------------------------------------------------
-- Puerto: poligono que delimita la superficie operativa del puerto.
-- -----------------------------------------------------------------------------
CREATE TABLE puertos.puerto (
    puertoid  integer PRIMARY KEY,
    name      varchar(255) NOT NULL,
    ubicacion geometry(Polygon, 4326) NOT NULL
);

-- -----------------------------------------------------------------------------
-- Muelle: estructura de atraque dentro de un puerto. `calado` en metros.
-- -----------------------------------------------------------------------------
CREATE TABLE puertos.muelle (
    muelleid integer PRIMARY KEY,
    puertoid integer NOT NULL REFERENCES puertos.puerto (puertoid),
    calado   numeric(5,2)
);

-- -----------------------------------------------------------------------------
-- Amarres: posicion puntual donde se amarra un navio. Pertenece a un muelle.
-- -----------------------------------------------------------------------------
CREATE TABLE puertos.amarres (
    amarreid  integer PRIMARY KEY,
    muelleid  integer NOT NULL REFERENCES puertos.muelle (muelleid),
    ubicacion geometry(Point, 4326) NOT NULL
);

-- -----------------------------------------------------------------------------
-- Navio: buque que solicita servicio. `ubicacion` es su posicion actual, que
-- puede estar en alta mar (antes de arribar) o junto al muelle (ya amarrado).
-- -----------------------------------------------------------------------------
CREATE TABLE puertos.navio (
    navioid     integer PRIMARY KEY,
    name        varchar(80) NOT NULL,
    dimensiones varchar(50),
    ubicacion   geometry(Point, 4326) NOT NULL
);

-- -----------------------------------------------------------------------------
-- Equipos: maquinaria del puerto (gruas, etc.), georreferenciada.
-- -----------------------------------------------------------------------------
CREATE TABLE puertos.equipos (
    equiposid   integer PRIMARY KEY,
    puertoid    integer NOT NULL REFERENCES puertos.puerto (puertoid),
    descripcion varchar(255),
    ubicacion   geometry(Point, 4326) NOT NULL
);

-- -----------------------------------------------------------------------------
-- Solicitud: pedido de servicio de un navio a un puerto.
-- -----------------------------------------------------------------------------
CREATE TABLE puertos.solicitud (
    solicitudid     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    navioid         integer NOT NULL REFERENCES puertos.navio (navioid),
    puertoid        integer NOT NULL REFERENCES puertos.puerto (puertoid),
    amarreid        integer REFERENCES puertos.amarres (amarreid),
    fecha_solicitud date NOT NULL,
    fecha_arribo    date
);

-- -----------------------------------------------------------------------------
-- Amarresocupados: que amarre esta tomado, por que navio y desde cuando.
-- -----------------------------------------------------------------------------
CREATE TABLE puertos.amarresocupados (
    amarreid     integer PRIMARY KEY REFERENCES puertos.amarres (amarreid),
    navioid      integer NOT NULL REFERENCES puertos.navio (navioid),
    fecha_arribo date NOT NULL
);

-- -----------------------------------------------------------------------------
-- Indices espaciales GiST: sin ellos, cada ST_Contains / ST_DWithin degenera
-- en un scan secuencial con calculo geometrico fila por fila.
-- -----------------------------------------------------------------------------
CREATE INDEX puerto_ubicacion_idx  ON puertos.puerto  USING gist (ubicacion);
CREATE INDEX amarres_ubicacion_idx ON puertos.amarres USING gist (ubicacion);
CREATE INDEX navio_ubicacion_idx   ON puertos.navio   USING gist (ubicacion);
CREATE INDEX equipos_ubicacion_idx ON puertos.equipos USING gist (ubicacion);

-- Indices sobre las FK mas consultadas
CREATE INDEX muelle_puertoid_idx    ON puertos.muelle    (puertoid);
CREATE INDEX amarres_muelleid_idx   ON puertos.amarres   (muelleid);
CREATE INDEX equipos_puertoid_idx   ON puertos.equipos   (puertoid);
CREATE INDEX solicitud_puertoid_idx ON puertos.solicitud (puertoid);
CREATE INDEX solicitud_navioid_idx  ON puertos.solicitud (navioid);
